/*
  Dado un numero entero que se introduce por teclado, determinar si es positivo, negativo o nulo.
*/

entero numero

Inicio 

   Escriba "Ingresa un numero: "
   Lea numero

    Si numero > 0 Entonces
        Escriba "El numero es positivo."
    Sino
        Si numero < 0 Entonces
            Escriba "El numero es negativo."
        Sino
            Escriba "El numero es nulo."
        Fin Si
    Fin Si

Fin