package presentacion;
import controlador.PreguntasController;
import javax.swing.JOptionPane;
/**
 *
 * @author Johan Rengifo
 */
public class UI extends javax.swing.JFrame {

    PreguntasController game = new PreguntasController();
    int num_pregunta = 0;

    public UI() {
        initComponents();
        // Labels Preguntas y Respuestas
        mostrarPregunta();
        // Puntaje
        lblPuntos.setText("Puntos: 0");
    }

    private void btnRespuestaActionPerformed(java.awt.event.ActionEvent evt, int numeroRespuesta) {
        String respuestaUsuario = obtenerRespuestaUsuario(numeroRespuesta);
        game.evaluarRespuesta(respuestaUsuario);

        // Avanzar a la siguiente pregunta
         num_pregunta++;

        // Mostrar la siguiente pregunta
        mostrarPregunta();
        
        // Puntos
        actualizarPuntos();
    }
    
    private void actualizarPuntos() {
        // Obtén los puntos del controlador y actualiza la etiqueta
        int puntos = game.obtenerPuntos();
        lblPuntos.setText("Puntos: " + puntos);
    }

    private String obtenerRespuestaUsuario(int numeroRespuesta) {
        switch (numeroRespuesta) {
            case 1:
                return "A";
            case 2:
                return "B";
            case 3:
                return "C";
            case 4:
                return "D";
            case 5:
                registrarPreguntas();
            default:  
                return "";
        }
    }

    public void mostrarPregunta() {
        String[][] preguntas = game.obtenerPreguntas();
        
        if (num_pregunta < preguntas.length) {
            // Lista Pregunta - Respuesta
            lblPregunta.setText(game.mostrarPregunta(num_pregunta, 0));
            // Lista Respuesta - Pregunta
            btnRespuesta1.setText(game.mostrarRespuestas(num_pregunta, 1));
            btnRespuesta2.setText(game.mostrarRespuestas(num_pregunta, 2));
            btnRespuesta3.setText(game.mostrarRespuestas(num_pregunta, 3));
            btnRespuesta4.setText(game.mostrarRespuestas(num_pregunta, 4));
            // Puntos
        } else {
            System.out.println("Fin del juego. Todas las preguntas han sido respondidas.");
        }
    }
    
    public void registrarPreguntas() {
        
        String nuevaPregunta = JOptionPane.showInputDialog(this, "Ingrese el contenido de la pregunta:");

        if (nuevaPregunta != null && !nuevaPregunta.isEmpty()) {
            String[] nuevasRespuestas = new String[4];
            nuevasRespuestas[0] = JOptionPane.showInputDialog(this, "Ingrese el contenido de la respuesta A:");
            nuevasRespuestas[1] = JOptionPane.showInputDialog(this, "Ingrese el contenido de la respuesta B:");
            nuevasRespuestas[2] = JOptionPane.showInputDialog(this, "Ingrese el contenido de la respuesta C:");
            nuevasRespuestas[3] = JOptionPane.showInputDialog(this, "Ingrese el contenido de la respuesta D:");

            String nuevaRespuestaCorrecta = JOptionPane.showInputDialog(this, "Ingrese la respuesta correcta (A, B, C, D):");

            if (nuevaRespuestaCorrecta != null && !nuevaRespuestaCorrecta.isEmpty()
                    && nuevasRespuestas[0] != null && !nuevasRespuestas[0].isEmpty()
                    && nuevasRespuestas[1] != null && !nuevasRespuestas[1].isEmpty()
                    && nuevasRespuestas[2] != null && !nuevasRespuestas[2].isEmpty()
                    && nuevasRespuestas[3] != null && !nuevasRespuestas[3].isEmpty()) {
                // Manda a Controlador los Valores Obtenidos
                game.agregarPregunta(nuevaPregunta, nuevasRespuestas, nuevaRespuestaCorrecta);
                JOptionPane.showMessageDialog(this, "Pregunta registrada exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al ingresar la pregunta. Asegúrese de proporcionar información válida.");
            }
        }
    }
    
    // ///////////////////////////////////////////////////////////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblPregunta = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        RegPreguntas = new javax.swing.JButton();
        btnRespuesta1 = new javax.swing.JButton();
        btnRespuesta2 = new javax.swing.JButton();
        btnRespuesta3 = new javax.swing.JButton();
        btnRespuesta4 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPregunta.setFont(new java.awt.Font("Footlight MT Light", 0, 24)); // NOI18N
        lblPregunta.setForeground(new java.awt.Color(255, 255, 255));
        lblPregunta.setText("jLabel2");
        getContentPane().add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        lblPuntos.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lblPuntos.setForeground(new java.awt.Color(204, 255, 255));
        lblPuntos.setText("Puntos");
        getContentPane().add(lblPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        RegPreguntas.setText("Registrar Preguntas");
        RegPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegPreguntasActionPerformed(evt);
            }
        });
        getContentPane().add(RegPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btnRespuesta1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRespuesta1.setText("A");
        btnRespuesta1.setAutoscrolls(true);
        btnRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuesta1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        btnRespuesta2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRespuesta2.setText("B");
        btnRespuesta2.setAutoscrolls(true);
        btnRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuesta2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        btnRespuesta3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRespuesta3.setText("C");
        btnRespuesta3.setAutoscrolls(true);
        btnRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuesta3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRespuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        btnRespuesta4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRespuesta4.setText("D");
        btnRespuesta4.setAutoscrolls(true);
        btnRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuesta4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRespuesta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/Fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 400));

        pack();
    }// </editor-fold>                        

    private void btnRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        btnRespuestaActionPerformed(evt, 1);
    }                                             

    private void btnRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        btnRespuestaActionPerformed(evt, 2);
    }                                             

    private void btnRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        btnRespuestaActionPerformed(evt, 3);
    }                                             

    private void btnRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        btnRespuestaActionPerformed(evt, 4);
    }                                             

    private void RegPreguntasActionPerformed(java.awt.event.ActionEvent evt) {                                             
        btnRespuestaActionPerformed(evt, 5);
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton RegPreguntas;
    private javax.swing.JButton btnRespuesta1;
    private javax.swing.JButton btnRespuesta2;
    private javax.swing.JButton btnRespuesta3;
    private javax.swing.JButton btnRespuesta4;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblPuntos;
    // End of variables declaration                   
}
