package unimayor;
// Importaciones
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VntPrin extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Alumno> listaAlumnos = new ArrayList<>();
    
   
    public VntPrin() {
        initComponents();
        //Componentes
        setTitle("REGISTRO DE ALUMNOS");
        setSize(720, 520);
        setLocationRelativeTo(null);
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CARRERA");
        modelo.addColumn("GRUPO");
        modelo.addColumn("SEMESTRE");
        modelo.addColumn("PROMEDIO");
        refrescarTabla();
    }
    
    // Refrescar Tabla
    public void refrescarTabla() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        
        for (Alumno alumno : listaAlumnos) {
            Object[] a = new Object[5];
            a[0] = alumno.getNombre();
            a[1] = alumno.getCarrera();
            a[2] = alumno.getGrupo();
            a[3] = alumno.getSemestre();
            a[4] = alumno.getPromedio();
            modelo.addRow(a);
        }
        
        tblregistroalumno.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblregistroalumno = new javax.swing.JTable();
        btnEliminarTd = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        CBOgrupo = new javax.swing.JComboBox<>();
        jlgrupo = new javax.swing.JLabel();
        jlpromedio = new javax.swing.JLabel();
        SPMpromedio = new javax.swing.JSpinner();
        jlsemestre = new javax.swing.JLabel();
        CBOsemestre = new javax.swing.JComboBox<>();
        txtnombre = new javax.swing.JTextField();
        jlnombre = new javax.swing.JLabel();
        jlcarrera = new javax.swing.JLabel();
        CBOcarrera = new javax.swing.JComboBox<>();
        btnEliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblregistroalumno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblregistroalumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NOMBRE", "CARRERA", "GRUPO", "SEMESTRE", "PROMEDIO"
            }
        ));
        jScrollPane1.setViewportView(tblregistroalumno);

        btnEliminarTd.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarTd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnEliminarTd.setText("Eliminar Todo");
        btnEliminarTd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTdActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 102));
        btnEditar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnagregar.setBackground(new java.awt.Color(204, 255, 204));
        btnagregar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        CBOgrupo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CBOgrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        CBOgrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOgrupoActionPerformed(evt);
            }
        });

        jlgrupo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlgrupo.setText("Grupo:");

        jlpromedio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlpromedio.setText("Promedio:");

        SPMpromedio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SPMpromedio.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1L), Long.valueOf(0L), Long.valueOf(5L), Long.valueOf(1L)));

        jlsemestre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlsemestre.setText("Semestre:");

        CBOsemestre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CBOsemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "primero", "segundo", "tercero", "cuarto", "quinto", "sexto", "septimo", "octavo", "noveno ", "decimo" }));

        txtnombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jlnombre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlnombre.setText("Nombres:");

        jlcarrera.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlcarrera.setText("Carrera Universitaria:");

        CBOcarrera.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        CBOcarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INGENIERIA INFORMATICA", "TEGNOLOGIA EN DESARROLLO DE SOFWARE" }));

        btnEliminar1.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBOsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CBOcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBOgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jlpromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(SPMpromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnagregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnEliminarTd, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlcarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBOcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlgrupo)
                    .addComponent(CBOgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlpromedio)
                    .addComponent(SPMpromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlsemestre)
                    .addComponent(CBOsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEliminarTd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            int filaSeleccionada = tblregistroalumno.getSelectedRow();

            if (filaSeleccionada == -1) {
                JOptionPane.showMessageDialog(null, "Por favor, seleccione un alumno para editar.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Alumno alumno = listaAlumnos.get(filaSeleccionada);
            alumno.setNombre(txtnombre.getText());
            alumno.setCarrera(CBOcarrera.getSelectedItem().toString());
            alumno.setGrupo(Integer.parseInt(CBOgrupo.getSelectedItem().toString()));
            alumno.setSemestre(CBOsemestre.getSelectedItem().toString());
            alumno.setPromedio(Double.parseDouble(SPMpromedio.getValue().toString()));

            refrescarTabla();

            JOptionPane.showMessageDialog(null, "El alumno ha sido actualizado correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Error al editar el alumno.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        try{
            Alumno alumno = new Alumno();
            alumno.setNombre(txtnombre.getText());
            alumno.setCarrera(CBOcarrera.getSelectedItem().toString());
            alumno.setGrupo(Integer.parseInt(CBOgrupo.getSelectedItem().toString()));
            alumno.setSemestre(CBOsemestre.getSelectedItem().toString());
            alumno.setPromedio(Double.parseDouble(SPMpromedio.getValue().toString()));

            listaAlumnos.add(alumno);
            refrescarTabla();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR EL USUARIO");
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void CBOgrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOgrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBOgrupoActionPerformed

    private void btnEliminarTdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTdActionPerformed
        try {
        if (!listaAlumnos.isEmpty()) {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar todos los registros?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                listaAlumnos.clear();
                refrescarTabla();
                JOptionPane.showMessageDialog(null, "Todos los registros han sido eliminados correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay registros para eliminar.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al eliminar los registros.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarTdActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        try {
        int filaSeleccionada = tblregistroalumno.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un alumno para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar este alumno?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            listaAlumnos.remove(filaSeleccionada);
            refrescarTabla();
            JOptionPane.showMessageDialog(null, "El alumno ha sido eliminado correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al eliminar el alumno.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VntPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VntPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VntPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VntPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VntPrin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBOcarrera;
    private javax.swing.JComboBox<String> CBOgrupo;
    private javax.swing.JComboBox<String> CBOsemestre;
    private javax.swing.JSpinner SPMpromedio;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminarTd;
    private javax.swing.JButton btnagregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlcarrera;
    private javax.swing.JLabel jlgrupo;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JLabel jlpromedio;
    private javax.swing.JLabel jlsemestre;
    private javax.swing.JTable tblregistroalumno;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
